name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Usamos una acción oficial y actualizada
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug

      - name: Upload APK
        # Actualizado a v4 para evitar el error de depreciación
        uses: actions/upload-artifact@v4
        with:
          name: AmongUsMod-APK
          path: bin/*.apk
