name: Build APK Final
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Instalamos las versiones de 2026 de las librer√≠as
          sudo apt-get install -y \
            python3-pip build-essential git python3-dev ffmpeg libsdl2-dev \
            libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            openjdk-17-jdk unzip zip libncurses6 libncursesw6 libstdc++6 \
            python3-setuptools autoconf libtool pkg-config ant
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Aceptamos licencias y compilamos
          yes | buildozer -v android debug
        continue-on-error: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AmongUsMod-Instalable
          path: bin/*.apk
